# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('upload', models.FileField(upload_to='media/music', verbose_name='Upload your file')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
